### ISSUE TITLE
Interpreting the permutation output from rabbit ordering

### ISSUE THREAD

**Issue by bvignesh** [araij/rabbit_order#1]
Hi, 

I am benchmarking the performance of an SpMV computation after rabbit ordering the input graph. How should the output of the demo program be interpreted? 

Looking at the README, it looks like the output should be interpreted as vertex 8 needs to be remapped to vertex 0 [vertex 8 ==> vertex 0] (first line in the example given)

However, I am getting slowdowns with the above interpretation. Flipping the direction of the permutation (i.e. vertex 0 needs to be remapped to vertex 8) gives performance improvements. 

Is my initial interpretation of the permutation backwards or is this an issue peculiar to a set of input graphs?

Thanks!

**Comment by araij** [comment]
@bvignesh Thank you very much for verification and reporting. The README was wrong as you pointed out. I'm sorry for making you confused. Commit f67a79e fixes the README.
