### ISSUE TITLE
Is Rabbit Ordering supposed to be used only for symmetric graphs?

### ISSUE THREAD

**Issue by bvignesh** [araij/rabbit_order#2]
Hi, 

I am trying to produce rabbit-ordered versions of some directed (i.e. not symmetric) graphs. I noticed that the line 33-40 in the `make_adj_list(...)` function in reorder.cc symmetrizes the edgelist. Does this mean that the rabbit order code is only supposed to be used with undirected graphs (and that the code does not support directed graphs)? 

I was not sure if the code provided can also handle directed graphs because the IPDPS paper (at the end of Section II) also mentions that the algorithms described are for undirected (symmetric) graphs. 

Thanks!

**Comment by atmughrabi** [comment]
Hi although I am not the maintainer of the code, I believe when you want to use an incremental aggregation equation for directed graphs you have to change it to take in/out degrees into consideration.

**Comment by araij** [comment]
@bvignesh 
> Does this mean that the rabbit order code is only supposed to be used with undirected graphs (and that the code does not support directed graphs)?

Yes, `rabbit_order::aggregate(adj)` assumes that `adj` is symmetric. However, just like `demo/reorder.cc`, you can reorder directed graphs by symmetrizing the edges. The IPDPS paper shows the results obtained in this way. Most of the graphs used in the experiments (Table II) are directed.

@atmughrabi Thank you for your comment. 

> I believe when you want to use an incremental aggregation equation for directed graphs you have to change it to take in/out degrees into consideration.

I agree, but Newman and Girvan recommend ignoring edge directions for community detection based on modularity [1]:
> However, we have found that in many cases it is better to ignore the directed nature of a network in calculating community structure. Often an edge acts simply as an indication of a connection between two nodes, and its direction is unimportant.

[1] M. E. J. Newman and M. Girvan, “Finding and evaluating community structure in networks,” Phys. Rev. E, vol. 69, no. 2, p. 026113, Feb. 2004.

**Comment by bvignesh** [comment]
Thanks both for your responses!

@araij Just to make sure that I understood your point -- you are suggesting that even for directed graphs, symmetrizing the edgelist and then running rabbit-order will still produce a correct permutation? 

Alternatively, I was wondering if I could just not symmetrize the edgelist (as done in lines 33-40 of `reorder.cc`) and send a directed adj as input to the `reorder(...)` function (line 183)? (The reason I am asking this is because I was trying to modify the rabbit order code to produce the edgelist of the reordered graph; instead of a mapping from old to new vertex Ids)

Thanks!

**Comment by araij** [comment]
@bvignesh 
> even for directed graphs, symmetrizing the edgelist and then running rabbit-order will still produce a correct permutation?

Yes. Here "correct" means that the permutation improves locality as intended. This is because, Rabbit Order is based on modularity-based community detection, which captures community structures better when edge directions are ignored (i.e., symmetrized) as stated in [1] (<https://github.com/araij/rabbit_order/issues/2#issuecomment-900898573>).

> I was wondering if I could just not symmetrize the edgelist (as done in lines 33-40 of reorder.cc) and send a directed adj as input to the reorder(...) function (line 183)?

You can, but giving directed `adj` will degrade the quality (i.e., locality) of the produced permutation.

> I was trying to modify the rabbit order code to produce the edgelist of the reordered graph

To do so, you need to keep both original and symmetrized copies of a directed graph.

```
directed_adj <- adjacency list of a directed graph
undirected_adj <- symmetrized adjacency list of directed_adj

// L187 and L188 in reorder.cc
g <- rabbit_order::aggregate(undirected_adj)
p <- rabbit_order::compute_perm(g)

permute(directed_adj, p)
```

Thank you for your interest in Rabbit Order!

**Comment by bvignesh** [comment]
Thanks for the clear explanation! You have addressed all my doubts so I am closing this issue
